name: Release Action
on: workflow_dispatch

permissions: write-all

env:
  PROJECT_NAME: EllawyFS

jobs:
  build:
    name: ${{ matrix.name }}
    strategy:
      matrix:
        include:
          - name: Android
            os: macos-15
            buildArgs: "android -final -D officialBuild"
            artifactName: Android
            artifactPath: "export/release/android/bin/app/build/outputs/apk/release/*.apk"
          - name: iOS
            os: macos-15
            buildArgs: "ios -final -nosign"
            artifactName: iOS
            artifactPath: "export/release/ios/build/Release-iphoneos/*.ipa"
    uses: ./.github/workflows/build.yml
    with:
        name: ${{ matrix.name }}
        os: ${{ matrix.os }}
        buildArgs: ${{ matrix.buildArgs }}
        artifactName: ${{ matrix.artifactName }}
        artifactPath: ${{ matrix.artifactPath }}

  Releaser:
    needs: [build]
    runs-on: ubuntu-latest
    permissions: write-all
    steps:
      - name: Download all workflow run artifacts
        uses: actions/download-artifact@v4

      - name: Zip Artifacts
        run: |
           zip -r Android.zip Android/
           zip -r iOS.zip iOS/

      - name: Publish The Release
        uses: softprops/action-gh-release@v2
        with:
          name: "1.0.0"
          tag_name: "1.0.0"
          make_latest: false
          files: |
            Android.zip
            iOS.zip
